# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.20

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/tasit-sdk

    steps:
      - checkout

      - run:
          name: Installing npm
          command: "sudo npm install -g npm@latest"

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #      - dependency-cache-{{ checksum "package-lock.json" }}
      # fallback to using the latest cache if no exact match is found
      #      - dependency-cache-

      - run:
          name: Bootstrapping packages
          command: npm run bootstrap

      #- save_cache:
      #    paths:
      #      - ./node_modules
      #    key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Running test suite
          command: npm test
